# Library:
* A Python library is a collection of related modules. It contains bundles of code that can be used repeatedly in different programs. It makes Python Programming simpler and convenient for the programmer. As we don’t need to write the same code again and again for different programs. Python libraries play a very vital role in fields of Machine Learning, Data Science, Data Visualization, etc.

1. numpy
2. pandas
3. matlab
4. sea born

# Numpy:
* NumPy is a Python library used for working with arrays.

* It also has functions for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

* NumPy stands for Numerical Python.

In [1]:
!pip install numpy


In [2]:
import numpy as np

a= np.array([1,2,3,4,5]) #1d
b= np.array([[6,7,8],[8,9,10]]) #2d
c= np.array([[[11,12,13],[14,15,16],[17,18,19]]]) #3d
print(a)
print(b)
print(c)

[1 2 3 4 5]
[[ 6  7  8]
 [ 8  9 10]]
[[[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [3]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [4]:
np.zeros((2,3,4)) #shapes,row,col

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [5]:
np.ones((3,2,2)) #shapes,row,col

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [6]:
d= np.arange(1,20,2)
print(d)

[ 1  3  5  7  9 11 13 15 17 19]


In [7]:
e = np.full((2,2),4)
print(e)

[[4 4]
 [4 4]]


In [8]:
np.linspace(0,1,5) #start,end,no of values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
e1= np.full((3,3),5)
print(e1)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
f = np.eye(4) #identitry matrix
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr = np.array([1,2,3,4], dtype='f')
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [12]:
#integer

arr = np.array([1,2,3,4],dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [13]:
# changing data  type from float to int

arr = np.array([1.1,2.1,3.1])
newarr= arr.astype('i')
print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [14]:
# changing data  type from int to boolean

arr = np.array([1,0,3,0,7,6,0])
newarr= arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True False  True  True False]
bool


# NumPy Array Copy vs View
* The Difference Between Copy and View
   * The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

   * The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

   * The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [15]:
# copy method

arr = np.array([1,2,3,4,5,6])
x= arr.copy()
arr[2] =9
print(arr)
print(x)

[1 2 9 4 5 6]
[1 2 3 4 5 6]


In [16]:
#view method

arr= np.array([1,2,3,4,5,6])
x =arr.view()

arr[0]=9

print(arr)
print(x)

[9 2 3 4 5 6]
[9 2 3 4 5 6]


In [17]:
#reshaping array

# 1d to 2d

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)

newarr = arr.reshape(6,2)

print(newarr)

12
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [18]:
# matrix

x= np.array([[1,2],[3,4]])
y= np.array([[5,6],[7,8]])

print(np.add(x,y))


[[ 6  8]
 [10 12]]


In [19]:
#sub
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [20]:
#mul

print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [21]:
#div

print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [22]:
#sqaure root

print(np.sqrt(x))
print(np.sqrt(y))

[[1.         1.41421356]
 [1.73205081 2.        ]]
[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [23]:
#sorting order

arr = np.array([3,2,0,5,9,45,2,4,12,1,7,2,9])
print(np.sort(arr))

[ 0  1  2  2  2  3  4  5  7  9  9 12 45]


#NumPy Array Slicing
* Slicing arrays
  * Slicing in python means taking elements from one given index to another given index.

  * We pass slice instead of index like this: [start:end].

  * We can also define the step, like this: [start:end:step].

  * If we don't pass start its considered 0

  * If we don't pass end its considered length of array in that dimension

  * If we don't pass step its considered 1

In [24]:
#slicing methods

arr =np.array([1,2,3,4,5,6,7])
print(arr[1:12])



[2 3 4 5 6 7]


In [25]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:])

[2 3 4 5 6 7]


In [26]:
arr=np.array([1,2,3,4,5,6])
print(arr[:5])

[1 2 3 4 5]


In [27]:
arr=np.array([1,2,3,4,5,6])
print(arr[-3:-1])

[4 5]


In [28]:
# 2dimensional slicing

arr=np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [16,17,18,19,20]])
print(arr[2,1:3])


[17 18]


In [29]:

arr= np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [16,17,18,19,20]])

print(arr[0:2,4])

[ 5 10]
